name = "junze-anju"
compatibility_date = "2025-01-01"
pages_build_output_dir = "dist"

[vars]
JWT_SECRET = "junze-anju-secret-key-2026"
ADMIN_PASSWORD = "admin123"

[[d1_databases]]
binding = "DB"
database_name = "junze-anju-db"
database_id = "f5f5ba7d-c5d4-4d62-9658-69a8c2b2bacb"

[[kv_namespaces]]
binding = "KV"
id = "8a98f7fefdad4cc9970b322d882f3c05"
